import type { Citation } from "./api";

export interface ExportableTurn {
  question: string;
  answer: string;
  citations: Citation[];
  mode: "grounded" | "general";
}

const escapeHtml = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** Markdown version of an answer — for clipboard and .md download. */
export function toMarkdown(turn: ExportableTurn): string {
  const lines = [
    `# MediCite — Answer report`,
    "",
    `**Question:** ${turn.question}`,
    "",
    turn.mode === "general"
      ? "> Answered from general knowledge — not from the uploaded documents."
      : "> Answered from the uploaded documents, with page-level citations.",
    "",
    "## Answer",
    "",
    turn.answer,
  ];

  if (turn.citations.length) {
    lines.push("", "## Sources", "");
    for (const c of turn.citations) {
      const section = c.section_title ? ` · ${c.section_title}` : "";
      lines.push(`**[${c.marker}]** ${c.filename} — page ${c.page_number}${section}`);
      lines.push("", `> ${c.snippet.replace(/\n/g, " ")}`, "");
    }
  }

  lines.push(
    "",
    "---",
    "",
    `_Generated by MediCite on ${new Date().toLocaleString()}. Summarizes uploaded documents only — not medical advice. Verify against the cited source._`,
  );
  return lines.join("\n");
}

export async function copyAnswer(turn: ExportableTurn): Promise<void> {
  await navigator.clipboard.writeText(toMarkdown(turn));
}

export function downloadMarkdown(turn: ExportableTurn): void {
  const blob = new Blob([toMarkdown(turn)], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `medicite-answer-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Render a print-styled report in a new window and open the print dialog, where
 *  the browser's own "Save as PDF" produces the file. This avoids shipping a
 *  PDF-generation library for something the browser already does well. */
export function exportPdf(turn: ExportableTurn): void {
  const sources = turn.citations
    .map(
      (c) => `
      <div class="src">
        <div class="src-head">
          <span class="marker">${c.marker}</span>
          <strong>${escapeHtml(c.filename)}</strong>
          <span class="page">page ${c.page_number}${
            c.section_title ? ` · ${escapeHtml(c.section_title)}` : ""
          }</span>
        </div>
        <p class="snippet">${escapeHtml(c.snippet)}</p>
      </div>`,
    )
    .join("");

  const html = `<!doctype html>
<html><head><meta charset="utf-8" />
<title>MediCite — Answer report</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #0f172a;
         max-width: 720px; margin: 40px auto; padding: 0 24px; line-height: 1.6; }
  header { border-bottom: 2px solid #4f46e5; padding-bottom: 14px; margin-bottom: 24px;
           display: flex; align-items: baseline; justify-content: space-between; gap: 12px; }
  .brand { font-size: 20px; font-weight: 800; letter-spacing: -0.02em; }
  .brand span { color: #4f46e5; }
  .date { font-size: 12px; color: #64748b; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .08em;
       color: #64748b; margin: 28px 0 8px; }
  .question { font-size: 17px; font-weight: 700; margin: 0; }
  .badge { display: inline-block; font-size: 11px; font-weight: 600; padding: 3px 9px;
           border-radius: 999px; margin-top: 10px;
           background: ${turn.mode === "general" ? "#e0f2fe" : "#e0e7ff"};
           color: ${turn.mode === "general" ? "#075985" : "#3730a3"}; }
  .answer { white-space: pre-wrap; font-size: 15px; }
  .src { border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px 14px; margin-bottom: 10px;
         page-break-inside: avoid; }
  .src-head { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; font-size: 13px; }
  .marker { background: #4f46e5; color: #fff; border-radius: 5px; padding: 1px 7px;
            font-size: 11px; font-weight: 700; }
  .page { margin-left: auto; color: #4f46e5; font-weight: 600; font-size: 12px; }
  .snippet { white-space: pre-wrap; color: #475569; font-size: 12.5px; margin: 8px 0 0; }
  footer { margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 12px;
           font-size: 11px; color: #94a3b8; }
  @media print { body { margin: 0; } @page { margin: 18mm; } }
</style></head>
<body>
  <header>
    <div class="brand">Medi<span>Cite</span></div>
    <div class="date">${new Date().toLocaleString()}</div>
  </header>

  <h2>Question</h2>
  <p class="question">${escapeHtml(turn.question)}</p>
  <div class="badge">${
    turn.mode === "general"
      ? "General knowledge — not from the uploaded documents"
      : "Grounded in the uploaded documents"
  }</div>

  <h2>Answer</h2>
  <div class="answer">${escapeHtml(turn.answer)}</div>

  ${turn.citations.length ? `<h2>Sources</h2>${sources}` : ""}

  <footer>
    Generated by MediCite. Summarizes uploaded documents only — not medical advice.
    Always verify against the cited source.
  </footer>
</body></html>`;

  const win = window.open("", "_blank", "width=820,height=900");
  if (!win) return; // popup blocked — the Copy and .md options still work
  win.document.write(html);
  win.document.close();

  // Print once, whichever trigger fires first — `onload` normally, or the timer
  // as a fallback if the document was already complete.
  let printed = false;
  const printOnce = () => {
    if (printed) return;
    printed = true;
    win.print();
  };
  win.onload = printOnce;
  setTimeout(printOnce, 400);
}
